### ISSUE TITLE
Provide a pre push hook

### ISSUE THREAD

**Issue by nicosommi** [sumup-oss/foundry#243]
In the website we have foundry with lint staged on pre commit. In the website-backend we don't use foundry yet for this, but we use husky directly with a pre push hook instead.

I found the pre push experience much more pleasant, because I think the possibility of creating, updating, rebasing commits should be very fast, to take advantage of git as a tool for developers. Running these lint commands on every commit makes it very slow and IMO discourages the use of git... I always end up stashing and in the worst case loosing local changes. On the other hand, having a pre push hook seems as effective as the pre commit, with the benefit that you only run it once.

Maybe we can just add this config as an extra one without removing the existing one?

https://github.com/sumup-oss/foundry/blob/d215c3b200edba6380ff41a0b938f855bf10adc9/src/configs/husky/config.ts#L29

**Comment by connor-baer** [comment]
When we started Foundry, we discussed this at great length. The reason why we chose the pre-commit over the pre-push hook is a strong belief that each commit should be **self-contained** and should be **independent** of other commits. 

If a commit introduces lint errors that are fixed in a follow-up commit, they can no longer be reverted, removed, or cherry-picked independently. Thus, you lose a lot of the benefits of git. 

There are cases where this isn't (reasonably) enforceable. That's when the `--no-verify` flag provides an escape hatch.

**Comment by nicosommi** [comment]
It could happen that, indeed.

However if, for example, you usually squash commits from PRs into one, like we do in our website, we will not loose that benefit most of the time anyways.

I'm not suggesting to remove this config but adding another as an alternative.

Another point, is the frequency in which this happens. I'm not sure about your experience, but I never had such a strong need to cherry pick one commit and ran into a big issue trying to make it work, the nature of a cherry pick could go wrong anyways, do you have a specific case to look at? On the other hand, the dev experience while creating commits is an every day task...

**Comment by nicosommi** [comment]
In a second thought, this was just a personal idea and preference. So, if it was already discussed, I think is fair to close this one and only open again if there is more people interested.
